# basic options
title: The Working Title Podcast
author: GitHub User
email: workingtitlepodcastemail@gmail.com
description: Home of The Working Title Podcast
twitter_username: WorkingTitlePodcast
github_username:  WorkingTitlePodcast

# Build settings
markdown: kramdown
theme: minima
